services:

  cts_correction:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    image: cts_correction:latest 
    volumes:
      - ./cts-correction:/app
      - ./templates:/templates
      - ./static:/static
    environment:
      - TZ=$TZ
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - "80:80"
    depends_on:
      - database
      

  database:
    image: postgres:latest
    #container_name: my-postgres-container
    environment:
      - TZ=$TZ
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB    
    ports:
      - "5432:5432"
