services:

  cts_correction:
    stdin_open: true
    tty: true
    image: cts_correction:latest 
    volumes:
      - ./cts-correction:/app
      - ./sample_data:/app/data
      - ./templates:/templates
      - ./static:/static
    env_file:
      - ./.env
    ports:
      - "8011:80"
    networks:
      - irevs_cts_net
    depends_on:
      database:
        condition: service_healthy
    restart: always
    logging:
      options:
        max-size: 10m
      

  database:
    image: postgres:16.2
    #container_name: my-postgres-container
    privileged: true
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
    env_file:
      - ./.env
#    ports:
#      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - irevs_cts_net
    restart: always
    logging:
      options:
        max-size: 10m

networks:
  irevs_cts_net:
    external: true